const permisos = [
{'permisoName': 'VER LOS USUARIOS', 'permisoDescription': 'P_USUARIO'},
{'permisoName': 'AGREGAR LOS USUARIOS', 'permisoDescription': 'P_USUARIO'},
{'permisoName': 'EDITAR LOS USUARIOS', 'permisoDescription': 'P_USUARIO'},

{'permisoName': 'VER LOS ROLES', 'permisoDescription': 'P_ROL'},
{'permisoName': 'AGREGAR LOS ROLES', 'permisoDescription': 'P_ROL'},
{'permisoName': 'EDITAR LOS ROLES', 'permisoDescription': 'P_ROL'},

{'permisoName': 'VER LOS CATEGORIAS', 'permisoDescription': 'P_CATEGORIA'},
{'permisoName': 'AGREGAR LOS CATEGORIAS', 'permisoDescription': 'P_CATEGORIA'},
{'permisoName': 'EDITAR LOS CATEGORIAS', 'permisoDescription': 'P_CATEGORIA'},

{'permisoName': 'VER LOS SUBCATEGORIAS', 'permisoDescription': 'P_SUBCATEGORIA'},
{'permisoName': 'AGREGAR LOS SUBCATEGORIAS', 'permisoDescription': 'P_SUBCATEGORIA'},
{'permisoName': 'EDITAR LOS SUBCATEGORIAS', 'permisoDescription': 'P_SUBCATEGORIA'},

{'permisoName': 'VER LOS FICHAS', 'permisoDescription': 'P_FICHA'},
{'permisoName': 'AGREGAR LOS FICHAS', 'permisoDescription': 'P_FICHA'},
{'permisoName': 'EDITAR LOS FICHAS', 'permisoDescription': 'P_FICHA'},

{'permisoName': 'VER LOS INSTRUCTORES', 'permisoDescription': 'P_INSTRUCTOR'},
{'permisoName': 'AGREGAR LOS INSTRUCTORES', 'permisoDescription': 'P_INSTRUCTOR'},
{'permisoName': 'EDITAR LOS INSTRUCTORES', 'permisoDescription': 'P_INSTRUCTOR'},

{'permisoName': 'VER LOS UNIDADES DE MEDIDAS', 'permisoDescription': 'P_UM'},
{'permisoName': 'AGREGAR LOS UNIDADES DE MEDIDAS', 'permisoDescription': 'P_UM'},
{'permisoName': 'EDITAR LOS UNIDADES DE MEDIDAS', 'permisoDescription': 'P_UM'},

{'permisoName': 'VER LOS PRODUCTOS', 'permisoDescription': 'P_PRODUCTO'},
{'permisoName': 'AGREGAR LOS PRODUCTOS', 'permisoDescription': 'P_PRODUCTO'},
{'permisoName': 'EDITAR LOS PRODUCTOS', 'permisoDescription': 'P_PRODUCTO'},

{'permisoName': 'VER LOS HERRAMIENTAS', 'permisoDescription': 'P_HERRAMIETA'},
{'permisoName': 'AGREGAR LOS HERRAMIENTAS', 'permisoDescription': 'P_HERRAMIETA'},
{'permisoName': 'EDITAR LOS HERRAMIENTAS', 'permisoDescription': 'P_HERRAMIETA'},

{'permisoName': 'VER LOS PRESTAMOS', 'permisoDescription': 'P_PRESTAMO'},
{'permisoName': 'AGREGAR LOS PRESTAMOS', 'permisoDescription': 'P_PRESTAMO'},
{'permisoName': 'EDITAR LOS PRESTAMOS', 'permisoDescription': 'P_PRESTAMO'},

{'permisoName': 'VER LOS PEDIDO', 'permisoDescription': 'P_PEDIDO'},
{'permisoName': 'AGREGAR LOS PEDIDO', 'permisoDescription': 'P_PEDIDO'},
{'permisoName': 'EDITAR LOS PEDIDO', 'permisoDescription': 'P_PEDIDO'},

{'permisoName': 'VER LOS HISTORIA', 'permisoDescription': 'P_HISTORIAL'},

{'permisoName': 'VER LOS ESTADO', 'permisoDescription': 'P_ESTADO'},

{'permisoName': 'VER LOS PERMISOS', 'permisoDescription': 'P_PERMISO'},
{'permisoName': 'ASIGNAR PERMISO', 'permisoDescription': 'P_PERMISO'},
]


const roles = [
    {'rolName': 'ADMIN'},
    {'rolName': 'USUARIO'},
    {'rolName': 'SUBADMINISTRADOR'},
]

const insertarUnidades = [
        // Length (Longitud)
        { 'tipo': 'longitud', 'sigla': 'mm', 'nombre': 'Milímetro', 'equivalencia': 1 / 1000 },
        { 'tipo': 'longitud', 'sigla': 'cm', 'nombre': 'Centímetro', 'equivalencia': 1 / 100 },
        { 'tipo': 'longitud', 'sigla': 'm', 'nombre': 'Metro', 'equivalencia': 1 },
        { 'tipo': 'longitud', 'sigla': 'in', 'nombre': 'Pulgada', 'equivalencia': 0.0254 },
        { 'tipo': 'longitud', 'sigla': 'ft-us', 'nombre': 'Pie (US)', 'equivalencia': 0.3048 },
        { 'tipo': 'longitud', 'sigla': 'ft', 'nombre': 'Pie', 'equivalencia': 0.3048 },
        { 'tipo': 'longitud', 'sigla': 'mi', 'nombre': 'Milla', 'equivalencia': 1609.34 },
    
        // Area (Área)
        { 'tipo': 'area', 'sigla': 'mm²', 'nombre': 'Milímetro cuadrado', 'equivalencia': 1e-6 },
        { 'tipo': 'area', 'sigla': 'cm²', 'nombre': 'Centímetro cuadrado', 'equivalencia': 1e-4 },
        { 'tipo': 'area', 'sigla': 'm²', 'nombre': 'Metro cuadrado', 'equivalencia': 1 },
        { 'tipo': 'area', 'sigla': 'ha', 'nombre': 'Hectárea', 'equivalencia': 10000 },
        { 'tipo': 'area', 'sigla': 'km²', 'nombre': 'Kilómetro cuadrado', 'equivalencia': 1e6 },
        { 'tipo': 'area', 'sigla': 'in²', 'nombre': 'Pulgada cuadrada', 'equivalencia': 0.00064516 },
        { 'tipo': 'area', 'sigla': 'ft²', 'nombre': 'Pie cuadrado', 'equivalencia': 0.092903 },
        { 'tipo': 'area', 'sigla': 'ac', 'nombre': 'Acre', 'equivalencia': 4046.86 },
        { 'tipo': 'area', 'sigla': 'mi²', 'nombre': 'Milla cuadrada', 'equivalencia': 2.59e6 },
    
        // Mass (Masa)
        { 'tipo': 'masa', 'sigla': 'mcg', 'nombre': 'Microgramo', 'equivalencia': 1e-9 },
        { 'tipo': 'masa', 'sigla': 'mg', 'nombre': 'Miligramo', 'equivalencia': 1e-6 },
        { 'tipo': 'masa', 'sigla': 'g', 'nombre': 'Gramo', 'equivalencia': 1e-3 },
        { 'tipo': 'masa', 'sigla': 'kg', 'nombre': 'Kilogramo', 'equivalencia': 1 },
        { 'tipo': 'masa', 'sigla': 'oz', 'nombre': 'Onza', 'equivalencia': 0.0283495 },
        { 'tipo': 'masa', 'sigla': 'lb', 'nombre': 'Libra', 'equivalencia': 0.453592 },
        { 'tipo': 'masa', 'sigla': 'mt', 'nombre': 'Métrica tonelada', 'equivalencia': 1000 },
        { 'tipo': 'masa', 'sigla': 't', 'nombre': 'Tonelada', 'equivalencia': 1000 },
    
        // Volume (Volumen)
        { 'tipo': 'volumen', 'sigla': 'mm³', 'nombre': 'Milímetro cúbico', 'equivalencia': 1e-9 },
        { 'tipo': 'volumen', 'sigla': 'cm³', 'nombre': 'Centímetro cúbico', 'equivalencia': 1e-6 },
        { 'tipo': 'volumen', 'sigla': 'ml', 'nombre': 'Mililitro', 'equivalencia': 1e-6 },
        { 'tipo': 'volumen', 'sigla': 'l', 'nombre': 'Litro', 'equivalencia': 1e-3 },
        { 'tipo': 'volumen', 'sigla': 'kl', 'nombre': 'Kilolitro', 'equivalencia': 1 },
        { 'tipo': 'volumen', 'sigla': 'm³', 'nombre': 'Metro cúbico', 'equivalencia': 1 },
        { 'tipo': 'volumen', 'sigla': 'km³', 'nombre': 'Kilómetro cúbico', 'equivalencia': 1e9 },
        { 'tipo': 'volumen', 'sigla': 'tsp', 'nombre': 'Cucharadita', 'equivalencia': 4.92892e-3 },
        { 'tipo': 'volumen', 'sigla': 'Tbs', 'nombre': 'Cucharada', 'equivalencia': 1.47868e-2 },
        { 'tipo': 'volumen', 'sigla': 'in³', 'nombre': 'Pulgada cúbica', 'equivalencia': 1.63871e-5 },
        { 'tipo': 'volumen', 'sigla': 'fl-oz', 'nombre': 'Onza líquida', 'equivalencia': 2.95735e-5 },
        { 'tipo': 'volumen', 'sigla': 'cup', 'nombre': 'Taza', 'equivalencia': 0.236588 },
        { 'tipo': 'volumen', 'sigla': 'pnt', 'nombre': 'Pinta', 'equivalencia': 0.473176 },
        { 'tipo': 'volumen', 'sigla': 'qt', 'nombre': 'Cuarto de galón', 'equivalencia': 0.946353 },
        { 'tipo': 'volumen', 'sigla': 'gal', 'nombre': 'Galón', 'equivalencia': 3.78541 },
        { 'tipo': 'volumen', 'sigla': 'ft³', 'nombre': 'Pie cúbico', 'equivalencia': 0.0283168 },
        { 'tipo': 'volumen', 'sigla': 'yd³', 'nombre': 'Yarda cúbica', 'equivalencia': 0.764555 },
    
        // Volume Flow Rate (Tasa de flujo de volumen)
        { 'tipo': 'volumen_flujo', 'sigla': 'mm³/s', 'nombre': 'Milímetro cúbico por segundo', 'equivalencia': 1e-9 },
        { 'tipo': 'volumen_flujo', 'sigla': 'cm³/s', 'nombre': 'Centímetro cúbico por segundo', 'equivalencia': 1e-6 },
        { 'tipo': 'volumen_flujo', 'sigla': 'ml/s', 'nombre': 'Mililitro por segundo', 'equivalencia': 1e-6 },
        { 'tipo': 'volumen_flujo', 'sigla': 'cl/s', 'nombre': 'Centilitro por segundo', 'equivalencia': 1e-5 },
        { 'tipo': 'volumen_flujo', 'sigla': 'dl/s', 'nombre': 'Decilitro por segundo', 'equivalencia': 1e-4 },
        { 'tipo': 'volumen_flujo', 'sigla': 'l/s', 'nombre': 'Litro por segundo', 'equivalencia': 1e-3 },
        { 'tipo': 'volumen_flujo', 'sigla': 'l/min', 'nombre': 'Litro por minuto', 'equivalencia': 1.66667e-5 },
        { 'tipo': 'volumen_flujo', 'sigla': 'l/h', 'nombre': 'Litro por hora', 'equivalencia': 2.77778e-7 },
        { 'tipo': 'volumen_flujo', 'sigla': 'kl/s', 'nombre': 'Kilolitro por segundo', 'equivalencia': 1 },
        { 'tipo': 'volumen_flujo', 'sigla': 'kl/min', 'nombre': 'Kilolitro por minuto', 'equivalencia': 16.6667 },
        { 'tipo': 'volumen_flujo', 'sigla': 'kl/h', 'nombre': 'Kilolitro por hora', 'equivalencia': 0.277778 },
        { 'tipo': 'volumen_flujo', 'sigla': 'm³/s', 'nombre': 'Metro cúbico por segundo', 'equivalencia': 1 },
        { 'tipo': 'volumen_flujo', 'sigla': 'm³/min', 'nombre': 'Metro cúbico por minuto', 'equivalencia': 16.6667 },
        { 'tipo': 'volumen_flujo', 'sigla': 'm³/h', 'nombre': 'Metro cúbico por hora', 'equivalencia': 0.277778 },
        { 'tipo': 'volumen_flujo', 'sigla': 'km³/s', 'nombre': 'Kilómetro cúbico por segundo', 'equivalencia': 1e9 },
        { 'tipo': 'volumen_flujo', 'sigla': 'tsp/s', 'nombre': 'Cucharadita por segundo', 'equivalencia': 4.92892e-3 },
        { 'tipo': 'volumen_flujo', 'sigla': 'Tbs/s', 'nombre': 'Cucharada por segundo', 'equivalencia': 1.47868e-2 },
        { 'tipo': 'volumen_flujo', 'sigla': 'in³/s', 'nombre': 'Pulgada cúbica por segundo', 'equivalencia': 1.63871e-5 },
        { 'tipo': 'volumen_flujo', 'sigla': 'in³/min', 'nombre': 'Pulgada cúbica por minuto', 'equivalencia': 2.73159e-7 },
        { 'tipo': 'volumen_flujo', 'sigla': 'in³/h', 'nombre': 'Pulgada cúbica por hora', 'equivalencia': 4.55265e-9 },
        { 'tipo': 'volumen_flujo', 'sigla': 'fl-oz/s', 'nombre': 'Onza líquida por segundo', 'equivalencia': 2.95735e-5 },
        { 'tipo': 'volumen_flujo', 'sigla': 'fl-oz/min', 'nombre': 'Onza líquida por minuto', 'equivalencia': 4.92892e-4 },
        { 'tipo': 'volumen_flujo', 'sigla': 'fl-oz/h', 'nombre': 'Onza líquida por hora', 'equivalencia': 8.21487e-6 },
        { 'tipo': 'volumen_flujo', 'sigla': 'cup/s', 'nombre': 'Taza por segundo', 'equivalencia': 0.236588 },
        { 'tipo': 'volumen_flujo', 'sigla': 'pnt/s', 'nombre': 'Pinta por segundo', 'equivalencia': 0.473176 },
        { 'tipo': 'volumen_flujo', 'sigla': 'pnt/min', 'nombre': 'Pinta por minuto', 'equivalencia': 7.88627e-3 },
        { 'tipo': 'volumen_flujo', 'sigla': 'pnt/h', 'nombre': 'Pinta por hora', 'equivalencia': 1.31438e-4 },
        { 'tipo': 'volumen_flujo', 'sigla': 'qt/s', 'nombre': 'Cuarto de galón por segundo', 'equivalencia': 0.946353 },
        { 'tipo': 'volumen_flujo', 'sigla': 'gal/s', 'nombre': 'Galón por segundo', 'equivalencia': 3.78541 },
        { 'tipo': 'volumen_flujo', 'sigla': 'gal/min', 'nombre': 'Galón por minuto', 'equivalencia': 0.0630902 },
        { 'tipo': 'volumen_flujo', 'sigla': 'gal/h', 'nombre': 'Galón por hora', 'equivalencia': 0.0010515 },
        { 'tipo': 'volumen_flujo', 'sigla': 'ft³/s', 'nombre': 'Pie cúbico por segundo', 'equivalencia': 0.0283168 },
        { 'tipo': 'volumen_flujo', 'sigla': 'ft³/min', 'nombre': 'Pie cúbico por minuto', 'equivalencia': 4.71947e-4 },
        { 'tipo': 'volumen_flujo', 'sigla': 'ft³/h', 'nombre': 'Pie cúbico por hora', 'equivalencia': 7.86539e-6 },
        { 'tipo': 'volumen_flujo', 'sigla': 'yd³/s', 'nombre': 'Yarda cúbica por segundo', 'equivalencia': 0.764555 },
        { 'tipo': 'volumen_flujo', 'sigla': 'yd³/min', 'nombre': 'Yarda cúbica por minuto', 'equivalencia': 12.7426 },
        { 'tipo': 'volumen_flujo', 'sigla': 'yd³/h', 'nombre': 'Yarda cúbica por hora', 'equivalencia': 0.212377 },
    
        // Temperature (Temperatura)
        { 'tipo': 'temperatura', 'sigla': 'C', 'nombre': 'Celsius', 'equivalencia': 1 },
        { 'tipo': 'temperatura', 'sigla': 'F', 'nombre': 'Fahrenheit', 'equivalencia': 1 },
        { 'tipo': 'temperatura', 'sigla': 'K', 'nombre': 'Kelvin', 'equivalencia': 1 },
        { 'tipo': 'temperatura', 'sigla': 'R', 'nombre': 'Rankine', 'equivalencia': 1 },
    
        // Time (Tiempo)
        { 'tipo': 'tiempo', 'sigla': 'ns', 'nombre': 'Nanosegundo', 'equivalencia': 1e-9 },
        { 'tipo': 'tiempo', 'sigla': 'mu', 'nombre': 'Microsegundo', 'equivalencia': 1e-6 },
        { 'tipo': 'tiempo', 'sigla': 'ms', 'nombre': 'Milisegundo', 'equivalencia': 1e-3 },
        { 'tipo': 'tiempo', 'sigla': 's', 'nombre': 'Segundo', 'equivalencia': 1 },
        { 'tipo': 'tiempo', 'sigla': 'min', 'nombre': 'Minuto', 'equivalencia': 60 },
        { 'tipo': 'tiempo', 'sigla': 'h', 'nombre': 'Hora', 'equivalencia': 3600 },
        { 'tipo': 'tiempo', 'sigla': 'd', 'nombre': 'Día', 'equivalencia': 86400 },
        { 'tipo': 'tiempo', 'sigla': 'week', 'nombre': 'Semana', 'equivalencia': 604800 },
        { 'tipo': 'tiempo', 'sigla': 'month', 'nombre': 'Mes', 'equivalencia': 2.628e6 },
        { 'tipo': 'tiempo', 'sigla': 'year', 'nombre': 'Año', 'equivalencia': 3.154e7 },
    
        // Frequency (Frecuencia)
        { 'tipo': 'frecuencia', 'sigla': 'Hz', 'nombre': 'Hercio', 'equivalencia': 1 },
        { 'tipo': 'frecuencia', 'sigla': 'mHz', 'nombre': 'Milihercio', 'equivalencia': 1e-3 },
        { 'tipo': 'frecuencia', 'sigla': 'kHz', 'nombre': 'Kilohercio', 'equivalencia': 1e3 },
        { 'tipo': 'frecuencia', 'sigla': 'MHz', 'nombre': 'Megahercio', 'equivalencia': 1e6 },
        { 'tipo': 'frecuencia', 'sigla': 'GHz', 'nombre': 'Gigahercio', 'equivalencia': 1e9 },
        { 'tipo': 'frecuencia', 'sigla': 'THz', 'nombre': 'Terahercio', 'equivalencia': 1e12 },
        { 'tipo': 'frecuencia', 'sigla': 'rpm', 'nombre': 'Revoluciones por minuto', 'equivalencia': 0.0166667 },
        { 'tipo': 'frecuencia', 'sigla': 'deg/s', 'nombre': 'Grados por segundo', 'equivalencia': 1 },
        { 'tipo': 'frecuencia', 'sigla': 'rad/s', 'nombre': 'Radianes por segundo', 'equivalencia': 1 },
    
        // Speed (Velocidad)
        { 'tipo': 'velocidad', 'sigla': 'm/s', 'nombre': 'Metro por segundo', 'equivalencia': 1 },
        { 'tipo': 'velocidad', 'sigla': 'km/h', 'nombre': 'Kilómetro por hora', 'equivalencia': 0.277778 },
        { 'tipo': 'velocidad', 'sigla': 'm/h', 'nombre': 'Metro por hora', 'equivalencia': 0.000277778 },
        { 'tipo': 'velocidad', 'sigla': 'knot', 'nombre': 'Nudo', 'equivalencia': 0.514444 },
        { 'tipo': 'velocidad', 'sigla': 'ft/s', 'nombre': 'Pie por segundo', 'equivalencia': 0.3048 },
    
        // Pace (Ritmo)
        { 'tipo': 'ritmo', 'sigla': 's/m', 'nombre': 'Segundos por metro', 'equivalencia': 1 },
        { 'tipo': 'ritmo', 'sigla': 'min/km', 'nombre': 'Minutos por kilómetro', 'equivalencia': 60 },
        { 'tipo': 'ritmo', 'sigla': 's/ft', 'nombre': 'Segundos por pie', 'equivalencia': 3.28084 },
        { 'tipo': 'ritmo', 'sigla': 'min/km', 'nombre': 'Minutos por kilómetro', 'equivalencia': 60 },
    
        // Pressure (Presión)
        { 'tipo': 'presion', 'sigla': 'Pa', 'nombre': 'Pascal', 'equivalencia': 1 },
        { 'tipo': 'presion', 'sigla': 'hPa', 'nombre': 'Hectopascal', 'equivalencia': 100 },
        { 'tipo': 'presion', 'sigla': 'kPa', 'nombre': 'Kilopascal', 'equivalencia': 1e3 },
        { 'tipo': 'presion', 'sigla': 'MPa', 'nombre': 'Megapascal', 'equivalencia': 1e6 },
        { 'tipo': 'presion', 'sigla': 'bar', 'nombre': 'Bar', 'equivalencia': 1e5 },
        { 'tipo': 'presion', 'sigla': 'torr', 'nombre': 'Torr', 'equivalencia': 133.322 },
        { 'tipo': 'presion', 'sigla': 'psi', 'nombre': 'Libra por pulgada cuadrada', 'equivalencia': 6894.76 },
        { 'tipo': 'presion', 'sigla': 'ksi', 'nombre': 'Kilo-libra por pulgada cuadrada', 'equivalencia': 6.89476e6 },
    
        // Digital
        { 'tipo': 'digital', 'sigla': 'b', 'nombre': 'Bit', 'equivalencia': 1 },
        { 'tipo': 'digital', 'sigla': 'Kb', 'nombre': 'Kilobit', 'equivalencia': 1e3 },
        { 'tipo': 'digital', 'sigla': 'Mb', 'nombre': 'Megabit', 'equivalencia': 1e6 },
        { 'tipo': 'digital', 'sigla': 'Gb', 'nombre': 'Gigabit', 'equivalencia': 1e9 },
        { 'tipo': 'digital', 'sigla': 'Tb', 'nombre': 'Terabit', 'equivalencia': 1e12 },
        { 'tipo': 'digital', 'sigla': 'B', 'nombre': 'Byte', 'equivalencia': 8 },
        { 'tipo': 'digital', 'sigla': 'KB', 'nombre': 'Kilobyte', 'equivalencia': 8e3 },
        { 'tipo': 'digital', 'sigla': 'MB', 'nombre': 'Megabyte', 'equivalencia': 8e6 },
        { 'tipo': 'digital', 'sigla': 'GB', 'nombre': 'Gigabyte', 'equivalencia': 8e9 },
        { 'tipo': 'digital', 'sigla': 'TB', 'nombre': 'Terabyte', 'equivalencia': 8e12 },
    
        // Illuminance (Iluminancia)
        { 'tipo': 'iluminancia', 'sigla': 'lx', 'nombre': 'Lux', 'equivalencia': 1 },
        { 'tipo': 'iluminancia', 'sigla': 'ft-cd', 'nombre': 'Pie-candela', 'equivalencia': 10.7639 },
    
        // Parts-Per (Partes por)
        { 'tipo': 'partes_por', 'sigla': 'ppm', 'nombre': 'Partes por millón', 'equivalencia': 1e-6 },
        { 'tipo': 'partes_por', 'sigla': 'ppb', 'nombre': 'Partes por billón', 'equivalencia': 1e-9 },
        { 'tipo': 'partes_por', 'sigla': 'ppt', 'nombre': 'Partes por trillón', 'equivalencia': 1e-12 },
        { 'tipo': 'partes_por', 'sigla': 'ppq', 'nombre': 'Partes por cuatrillón', 'equivalencia': 1e-15 },
    
        // Voltage (Voltaje)
        { 'tipo': 'voltaje', 'sigla': 'V', 'nombre': 'Voltio', 'equivalencia': 1 },
        { 'tipo': 'voltaje', 'sigla': 'mV', 'nombre': 'Milivoltio', 'equivalencia': 1e-3 },
        { 'tipo': 'voltaje', 'sigla': 'kV', 'nombre': 'Kilovoltio', 'equivalencia': 1e3 },
    
        // Current (Corriente)
        { 'tipo': 'corriente', 'sigla': 'A', 'nombre': 'Amperio', 'equivalencia': 1 },
        { 'tipo': 'corriente', 'sigla': 'mA', 'nombre': 'Miliamperio', 'equivalencia': 1e-3 },
        { 'tipo': 'corriente', 'sigla': 'kA', 'nombre': 'Kiloamperio', 'equivalencia': 1e3 },
    
        // Power (Potencia)
        { 'tipo': 'potencia', 'sigla': 'W', 'nombre': 'Vatio', 'equivalencia': 1 },
        { 'tipo': 'potencia', 'sigla': 'mW', 'nombre': 'Milivatio', 'equivalencia': 1e-3 },
        { 'tipo': 'potencia', 'sigla': 'kW', 'nombre': 'Kilovatio', 'equivalencia': 1e3 },
        { 'tipo': 'potencia', 'sigla': 'MW', 'nombre': 'Megavatio', 'equivalencia': 1e6 },
        { 'tipo': 'potencia', 'sigla': 'GW', 'nombre': 'Gigavatio', 'equivalencia': 1e9 },
    
        // Apparent Power (Potencia aparente)
        { 'tipo': 'potencia_aparente', 'sigla': 'VA', 'nombre': 'Voltio-amperio', 'equivalencia': 1 },
        { 'tipo': 'potencia_aparente', 'sigla': 'mVA', 'nombre': 'Milivoltio-amperio', 'equivalencia': 1e-3 },
        { 'tipo': 'potencia_aparente', 'sigla': 'kVA', 'nombre': 'Kilovoltio-amperio', 'equivalencia': 1e3 },
        { 'tipo': 'potencia_aparente', 'sigla': 'MVA', 'nombre': 'Megavoltio-amperio', 'equivalencia': 1e6 },
        { 'tipo': 'potencia_aparente', 'sigla': 'GVA', 'nombre': 'Gigavoltio-amperio', 'equivalencia': 1e9 },
    
        // Reactive Power (Potencia reactiva)
        { 'tipo': 'potencia_reactiva', 'sigla': 'VAR', 'nombre': 'Voltio-amperio reactivo', 'equivalencia': 1 },
        { 'tipo': 'potencia_reactiva', 'sigla': 'mVAR', 'nombre': 'Milivoltio-amperio reactivo', 'equivalencia': 1e-3 },
        { 'tipo': 'potencia_reactiva', 'sigla': 'kVAR', 'nombre': 'Kilovoltio-amperio reactivo', 'equivalencia': 1e3 },
        { 'tipo': 'potencia_reactiva', 'sigla': 'MVAR', 'nombre': 'Megavoltio-amperio reactivo', 'equivalencia': 1e6 },
        { 'tipo': 'potencia_reactiva', 'sigla': 'GVAR', 'nombre': 'Gigavoltio-amperio reactivo', 'equivalencia': 1e9 },
    
        // Energy (Energía)
        { 'tipo': 'energia', 'sigla': 'Wh', 'nombre': 'Vatio-hora', 'equivalencia': 3600 },
        { 'tipo': 'energia', 'sigla': 'mWh', 'nombre': 'Milivatio-hora', 'equivalencia': 3.6 },
        { 'tipo': 'energia', 'sigla': 'kWh', 'nombre': 'Kilovatio-hora', 'equivalencia': 3.6e6 },
        { 'tipo': 'energia', 'sigla': 'MWh', 'nombre': 'Megavatio-hora', 'equivalencia': 3.6e9 },
        { 'tipo': 'energia', 'sigla': 'GWh', 'nombre': 'Gigavatio-hora', 'equivalencia': 3.6e12 },
        { 'tipo': 'energia', 'sigla': 'J', 'nombre': 'Julio', 'equivalencia': 1 },
        { 'tipo': 'energia', 'sigla': 'kJ', 'nombre': 'Kilojulio', 'equivalencia': 1e3 },
    
        // Temperature (Temperatura)
        { 'tipo': 'temperatura', 'sigla': '°C', 'nombre': 'Celsius', 'equivalencia': 1 },
        { 'tipo': 'temperatura', 'sigla': '°F', 'nombre': 'Fahrenheit', 'equivalencia': 1.8 },
        { 'tipo': 'temperatura', 'sigla': 'K', 'nombre': 'Kelvin', 'equivalencia': 1 },
    
        // Frequency (Frecuencia)
        { 'tipo': 'frecuencia', 'sigla': 'Hz', 'nombre': 'Hercio', 'equivalencia': 1 },
        { 'tipo': 'frecuencia', 'sigla': 'kHz', 'nombre': 'Kilohertz', 'equivalencia': 1e3 },
        { 'tipo': 'frecuencia', 'sigla': 'MHz', 'nombre': 'Megahertz', 'equivalencia': 1e6 },
        { 'tipo': 'frecuencia', 'sigla': 'GHz', 'nombre': 'Gigahertz', 'equivalencia': 1e9 },
    
        // Radioactivity (Radiactividad)
        { 'tipo': 'radiactividad', 'sigla': 'Bq', 'nombre': 'Becquerel', 'equivalencia': 1 },
        { 'tipo': 'radiactividad', 'sigla': 'Ci', 'nombre': 'Curie', 'equivalencia': 3.7e10 },
        { 'tipo': 'radiactividad', 'sigla': 'dpm', 'nombre': 'Desintegraciones por minuto', 'equivalencia': 60 },
        { 'tipo': 'radiactividad', 'sigla': 'Gy', 'nombre': 'Gray', 'equivalencia': 1 },
        { 'tipo': 'radiactividad', 'sigla': 'Sv', 'nombre': 'Sievert', 'equivalencia': 1 },
    
        // Angle (Ángulo)
        { 'tipo': 'angulo', 'sigla': '°', 'nombre': 'Grado', 'equivalencia': 1 },
        { 'tipo': 'angulo', 'sigla': '\'', 'nombre': 'Minuto de arco', 'equivalencia': 1/60 },
        { 'tipo': 'angulo', 'sigla': '"', 'nombre': 'Segundo de arco', 'equivalencia': 1/3600 },
        { 'tipo': 'angulo', 'sigla': 'rad', 'nombre': 'Radián', 'equivalencia': 57.2958 },
        { 'tipo': 'angulo', 'sigla': 'mrad', 'nombre': 'Miliradián', 'equivalencia': 57.2958/1000 },
        { 'tipo': 'angulo', 'sigla': 'grad', 'nombre': 'Grado centesimal', 'equivalencia': 0.9 },
        { 'tipo': 'angulo', 'sigla': 'gon', 'nombre': 'Gon', 'equivalencia': 0.9 },
    
        // Force (Fuerza)
        { 'tipo': 'fuerza', 'sigla': 'N', 'nombre': 'Newton', 'equivalencia': 1 },
        { 'tipo': 'fuerza', 'sigla': 'kN', 'nombre': 'Kilonewton', 'equivalencia': 1e3 },
        { 'tipo': 'fuerza', 'sigla': 'lbf', 'nombre': 'Libra-fuerza', 'equivalencia': 4.44822 },
        { 'tipo': 'fuerza', 'sigla': 'dyn', 'nombre': 'Dina', 'equivalencia': 1e-5 },
    
        // Torque (Par de torsión)
        { 'tipo': 'torque', 'sigla': 'Nm', 'nombre': 'Newton metro', 'equivalencia': 1 },
        { 'tipo': 'torque', 'sigla': 'lb-ft', 'nombre': 'Libra-pie', 'equivalencia': 1.35582 },
        { 'tipo': 'torque', 'sigla': 'kgf-m', 'nombre': 'Kilogramo-fuerza metro', 'equivalencia': 9.80665 },
        { 'tipo': 'torque', 'sigla': 'ozf-in', 'nombre': 'Onza-fuerza pulgada', 'equivalencia': 7.06155 },
    
];


export const defaultVariables ={
    permisos,
    roles,
    insertarUnidades
} 


/* 
export const conversionRates = {
    //-------------------------------------------------------------------------------------------------
   // logitud(comprimento)
    'mm': {
        'mm': 1,
        'cm': 0.1,
        'm': 0.001,
        'km': 0.000001,
        'in': 0.0393701,
        'ft': 0.00328084,
        'yd': 0.00109361,
        'mi': 0.000000621371,
    },
    'cm': {
        'mm': 10,
        'cm': 1,
        'm': 0.01,
        'km': 0.00001,
        'in': 0.393701,
        'ft': 0.0328084,
        'yd': 0.0109361,
        'mi': 0.00000621371,
    },
    'm': {
        'mm': 1000,
        'cm': 100,
        'm': 1,
        'km': 0.001,
        'in': 39.3701,
        'ft': 3.28084,
        'yd': 1.09361,
        'mi': 0.000621371,
    },
    'km': {
        'mm': 1000000,
        'cm': 100000,
        'm': 1000,
        'km': 1,
        'in': 39370.1,
        'ft': 3280.84,
        'yd': 1093.61,
        'mi': 0.621371,
    },
    'in': {
        'mm': 25.4,
        'cm': 2.54,
        'm': 0.0254,
        'km': 0.0000254,
        'in': 1,
        'ft': 0.0833333,
        'yd': 0.0277778,
        'mi': 0.0000157828,
    },
    'ft': {
        'mm': 304.8,
        'cm': 30.48,
        'm': 0.3048,
        'km': 0.0003048,
        'in': 12,
        'ft': 1,
        'yd': 0.333333,
        'mi': 0.000189394,
    },
    'yd': {
        'mm': 914.4,
        'cm': 91.44,
        'm': 0.9144,
        'km': 0.0009144,
        'in': 36,
        'ft': 3,
        'yd': 1,
        'mi': 0.000568182,
    },
    'mi': {
        'mm': 1609344,
        'cm': 160934,
        'm': 1609.34,
        'km': 1.60934,
        'in': 63360,
        'ft': 5280,
        'yd': 1760,
        'mi': 1,
    },
    //-------------------------------------------------------------------------------------------------
    // Area

    'mm²': {
        'mm²': 1,
        'cm²': 0.01,
        'm²': 0.000001,
        'km²': 1e-12,
        'in²': 0.0015500031,
        'ft²': 0.0000107639,
        'yd²': 0.00000119599,
        'ac': 2.47105381e-10,
        'ha': 1e-10,
    },
    'cm²': {
        'mm²': 100,
        'cm²': 1,
        'm²': 0.0001,
        'km²': 1e-10,
        'in²': 0.15500031,
        'ft²': 0.00107639,
        'yd²': 0.000119599,
        'ac': 2.47105381e-8,
        'ha': 1e-8,
    },
    'm²': {
        'mm²': 1000000,
        'cm²': 10000,
        'm²': 1,
        'km²': 0.000001,
        'in²': 1550.0031,
        'ft²': 10.7639,
        'yd²': 1.19599,
        'ac': 0.000247105,
        'ha': 0.0001,
    },
    'km²': {
        'mm²': 1e+12,
        'cm²': 1e+10,
        'm²': 1e+6,
        'km²': 1,
        'in²': 1.5500031e+9,
        'ft²': 1.076391e+7,
        'yd²': 1.19599e+6,
        'ac': 247.105,
        'ha': 100,
    },
    'in²': {
        'mm²': 645.16,
        'cm²': 6.4516,
        'm²': 0.00064516,
        'km²': 6.4516e-10,
        'in²': 1,
        'ft²': 0.00694444,
        'yd²': 0.000771605,
        'ac': 1.59422508e-7,
        'ha': 6.4516e-8,
    },
    'ft²': {
        'mm²': 92903.04,
        'cm²': 929.0304,
        'm²': 0.09290304,
        'km²': 9.290304e-8,
        'in²': 144,
        'ft²': 1,
        'yd²': 0.111111,
        'ac': 0.0000229568,
        'ha': 0.0000092903,
    },
    'yd²': {
        'mm²': 836127.36,
        'cm²': 8361.2736,
        'm²': 0.83612736,
        'km²': 8.3612736e-7,
        'in²': 1296,
        'ft²': 9,
        'yd²': 1,
        'ac': 0.000206612,
        'ha': 0.0000836127,
    },
    'ac': {
        'mm²': 4.04685642e+9,
        'cm²': 4.04685642e+7,
        'm²': 4046.85642,
        'km²': 0.00404686,
        'in²': 6.272640e+6,
        'ft²': 43560,
        'yd²': 4840,
        'ac': 1,
        'ha': 0.404686,
    },
    'ha': {
        'mm²': 1e+10,
        'cm²': 1e+8,
        'm²': 10000,
        'km²': 0.01,
        'in²': 1.5500031e+7,
        'ft²': 107639,
        'yd²': 11959.9,
        'ac': 2.47105,
        'ha': 1,
    },

    //-------------------------------------------------------------------------------------------------
    //Volumen
    'mm³': {
        'mm³': 1,
        'cm³': 0.001,
        'm³': 1e-9,
        'L': 1e-6,
        'mL': 0.001,
        'gal': 2.64172e-7,
        'fl oz': 3.3814e-5,
        'pt': 2.11338e-7,
        'qt': 1.05669e-7,
    },
    'cm³': {
        'mm³': 1000,
        'cm³': 1,
        'm³': 1e-6,
        'L': 0.001,
        'mL': 1,
        'gal': 0.000264172,
        'fl oz': 0.033814,
        'pt': 0.00211338,
        'qt': 0.00105669,
    },
    'm³': {
        'mm³': 1e+9,
        'cm³': 1e+6,
        'm³': 1,
        'L': 1000,
        'mL': 1e+6,
        'gal': 264.172,
        'fl oz': 33814,
        'pt': 2113.38,
        'qt': 1056.69,
    },
    'l': {
        'mm³': 1e+6,
        'cm³': 1000,
        'm³': 0.001,
        'L': 1,
        'mL': 1000,
        'gal': 0.264172,
        'fl oz': 33.814,
        'pt': 2.11338,
        'qt': 1.05669,
    },
    'ml': {
        'mm³': 1000,
        'cm³': 1,
        'm³': 1e-6,
        'L': 0.001,
        'mL': 1,
        'gal': 0.000264172,
        'fl oz': 0.033814,
        'pt': 0.00211338,
        'qt': 0.00105669,
    },
    'gal': {
        'mm³': 3.78541e+6,
        'cm³': 3785.41,
        'm³': 0.00378541,
        'L': 3.78541,
        'mL': 3785.41,
        'gal': 1,
        'fl oz': 128,
        'pt': 8,
        'qt': 4,
    },
    'fl oz': {
        'mm³': 29573.5,
        'cm³': 29.5735,
        'm³': 2.95735e-5,
        'L': 0.0295735,
        'mL': 29.5735,
        'gal': 0.0078125,
        'fl oz': 1,
        'pt': 0.0625,
        'qt': 0.03125,
    },
    'pt': {
        'mm³': 473176,
        'cm³': 473.176,
        'm³': 0.000473176,
        'L': 0.473176,
        'mL': 473.176,
        'gal': 0.125,
        'fl oz': 16,
        'pt': 1,
        'qt': 0.5,
    },
    'qt': {
        'mm³': 946353,
        'cm³': 946.353,
        'm³': 0.000946353,
        'L': 0.946353,
        'mL': 946.353,
        'gal': 0.25,
        'fl oz': 32,
        'pt': 2,
        'qt': 1,
    },
    //-------------------------------------------------------------------------------------------------
    // Masa

    'mg': {
        'mg': 1,
        'g': 0.001,
        'kg': 1e-6,
        't': 1e-9,
        'oz': 3.5274e-5,
        'lb': 2.2046e-6,
    },
    'g': {
        'mg': 1000,
        'g': 1,
        'kg': 0.001,
        't': 1e-6,
        'oz': 0.035274,
        'lb': 0.00220462,
    },
    'kg': {
        'mg': 1e+6,
        'g': 1000,
        'kg': 1,
        't': 0.001,
        'oz': 35.274,
        'lb': 2.20462,
    },
    't': {
        'mg': 1e+9,
        'g': 1e+6,
        'kg': 1000,
        't': 1,
        'oz': 35274,
        'lb': 2204.62,
    },
    'oz': {
        'mg': 28349.5,
        'g': 28.3495,
        'kg': 0.0283495,
        't': 2.835e-5,
        'oz': 1,
        'lb': 0.0625,
    },
    'lb': {
        'mg': 453592,
        'g': 453.592,
        'kg': 0.453592,
        't': 0.000453592,
        'oz': 16,
        'lb': 1,
    },
    //-------------------------------------------------------------------------------------------------
    //Capacidad
    'mL': {
        'mL': 1,
        'cL': 0.1,
        'dL': 0.01,
        'L': 0.001,
        'gal': 0.000264172,
        'qt': 0.00105669,
        'pt': 0.00211338,
        'fl oz': 0.033814,
    },
    'cL': {
        'mL': 10,
        'cL': 1,
        'dL': 0.1,
        'L': 0.01,
        'gal': 0.00264172,
        'qt': 0.0105669,
        'pt': 0.0211338,
        'fl oz': 0.33814,
    },
    'dL': {
        'mL': 100,
        'cL': 10,
        'dL': 1,
        'L': 0.1,
        'gal': 0.0264172,
        'qt': 0.105669,
        'pt': 0.211338,
        'fl oz': 3.3814,
    },
    'L': {
        'mL': 1000,
        'cL': 100,
        'dL': 10,
        'L': 1,
        'gal': 0.264172,
        'qt': 1.05669,
        'pt': 2.11338,
        'fl oz': 33.814,
    },
    'gal': {
        'mL': 3785.41,
        'cL': 378.541,
        'dL': 37.8541,
        'L': 3.78541,
        'gal': 1,
        'qt': 4,
        'pt': 8,
        'fl oz': 128,
    },
    'qt': {
        'mL': 946.353,
        'cL': 94.6353,
        'dL': 9.46353,
        'L': 0.946353,
        'gal': 0.25,
        'qt': 1,
        'pt': 2,
        'fl oz': 32,
    },
    'pt': {
        'mL': 473.176,
        'cL': 47.3176,
        'dL': 4.73176,
        'L': 0.473176,
        'gal': 0.125,
        'qt': 0.5,
        'pt': 1,
        'fl oz': 16,
    },
    'fl oz': {
        'mL': 29.5735,
        'cL': 2.95735,
        'dL': 0.295735,
        'L': 0.0295735,
        'gal': 0.0078125,
        'qt': 0.03125,
        'pt': 0.0625,
        'fl oz': 1,
    },
    //-------------------------------------------------------------------------------------------------
    // Talla (Ejemplo de guantes)
    talla: {
        tallaPequena: 1,  // 1 = Pequeña
        tallaMediana: 2,  // 2 = Mediana
        tallaGrande: 3,   // 3 = Grande
    },
}; */